### ISSUE TITLE
Backend - Betaling API intregatie

### ISSUE THREAD

**Issue by YoeriVereijken** [Justwouter/WDPR-SE2#10]
Betalingen worden correct via de API gehandeld
(API is yet to be provided)
kuch **Pascal** kuch

**Comment by Justwouter** [comment]
https://fakepay.azurewebsites.net
Er is een leuke react page aangemaakt om de betaling te handelen.
Zie bijgevoegde example POST request voor postman.


[WDPR.postman_collection.txt](https://github.com/Justwouter/WDPR-SE2/files/10336902/WDPR.postman_collection.txt)
