### ISSUE TITLE
Backend - Login/Registratie

### ISSUE THREAD

**Issue by Justwouter** [Justwouter/WDPR-SE2#11]
Gebruiker.Microservice
- Modellen voor Gebruiker, donateur, Artiest, Medewerker, Admin
- Roles

**Comment by Justwouter** [comment]
Yep en in de frontend ook een check inbouwen om bvb een valid email te hebben

**Comment by Studeeric** [comment]
Zie #35

**Comment by Studeeric** [comment]
Pure basis van Medewerkers en Bezoekers, later kunnen we meer toegen. Voor nu voldoende voor MVP

**Comment by Justwouter** [comment]
Closed met #35, werkt een tikkeltje janky maar goed genoeg.
